[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
absl-py = "2.0.0"
addict = "2.4.0"
aiofiles = "23.2.1"
altair = "5.2.0"
annotated-types = "0.6.0"
ansicon = "1.89.0"
anyio = "3.7.1"
asgiref = "3.7.2"
astunparse = "1.6.3"
attrs = "23.1.0"
basicsr = "1.4.2"
blessed = "1.20.0"
blinker = "1.6.2"
cachetools = "5.3.2"
certifi = "2023.11.17"
cffi = "1.16.0"
charset-normalizer = "3.3.2"
click = "8.1.7"
colorama = "0.4.6"
coloredlogs = "15.0.1"
contourpy = "1.2.0"
crispy-bootstrap5 = "2023.10"
cryptography = "41.0.7"
cycler = "0.12.1"
defusedxml = "0.7.1"
distlib = "*"
Django = "4.2"
django-allauth = "0.58.2"
django-crispy-forms = "2.1"
django-social-share = "2.3.0"
facexlib = "0.3.0"
fastapi = "0.104.1"
ffmpy = "0.3.1"
filelock = "3.12.4"
filetype = "1.2.0"
filterpy = "1.4.5"
Flask = "3.0.0"
flatbuffers = "23.5.26"
fonttools = "4.46.0"
fsspec = "2023.12.1"
future = "0.18.3"
gast = "0.5.4"
gfpgan = "1.3.8"
google-auth = "2.25.2"
google-auth-oauthlib = "1.1.0"
google-pasta = "0.2.0"
gradio = "3.50.2"
gradio_client = "0.6.1"
grpcio = "1.60.0"
h11 = "0.14.0"
h5py = "3.10.0"
httpcore = "1.0.2"
httpx = "0.25.2"
huggingface-hub = "0.19.4"
humanfriendly = "10.0"
idna = "3.6"
imageio = "2.33.0"
importlib-metadata = "7.0.0"
importlib-resources = "6.1.1"
inquirer = "3.1.4"
itsdangerous = "2.1.2"
Jinja2 = "3.1.2"
jinxed = "1.2.1"
jsonschema = "4.20.0"
jsonschema-specifications = "2023.11.2"
keras = "2.15.0"
kiwisolver = "1.4.5"
lazy_loader = "0.3"
libclang = "16.0.6"
llvmlite = "0.41.1"
lmdb = "1.4.1"
Markdown = "3.5.1"
MarkupSafe = "2.1.3"
matplotlib = "3.8.2"
ml-dtypes = "0.2.0"
mpmath = "1.3.0"
networkx = "3.2.1"
nose = "1.3.7"
nose2 = "0.14.0"
numba = "0.58.1"
numpy = "1.26.1"
oauthlib = "3.2.2"
onnx = "1.15.0"
onnxruntime = "1.16.3"
opencv-python = "4.8.1.78"
opt-einsum = "3.3.0"
orjson = "3.9.10"
packaging = "23.2"
pandas = "2.1.4"
Pillow = "10.1.0"
pipenv = "2023.10.3"
platformdirs = "3.11.0"
protobuf = "4.23.4"
psutil = "5.9.6"
psycopg2-binary = "2.9.9"
pyasn1 = "0.5.1"
pyasn1-modules = "0.3.0"
pycparser = "2.21"
pydantic = "2.5.2"
pydantic_core = "2.14.5"
pydub = "0.25.1"
PyJWT = "2.8.0"
pyparsing = "3.1.1"
pyreadline3 = "3.4.1"
python-dateutil = "2.8.2"
python-editor = "1.0.4"
python-multipart = "0.0.6"
python3-openid = "3.2.0"
pytz = "2023.3.post1"
PyYAML = "6.0.1"
readchar = "4.0.5"
realesrgan = "0.3.0"
referencing = "0.32.0"
requests = "2.31.0"
requests-oauthlib = "1.3.1"
rpds-py = "0.13.2"
rsa = "4.9"
scikit-image = "0.22.0"
scipy = "1.11.4"
semantic-version = "2.10.0"
six = "1.16.0"
sniffio = "1.3.0"
sqlparse = "0.4.4"
starlette = "0.27.0"
sympy = "1.12"
tb-nightly = "2.16.0a20231209"
tensorboard = "2.15.1"
tensorboard-data-server = "0.7.2"
tensorflow = "2.15.0"
tensorflow-estimator = "2.10.0"
tensorflow-intel = "2.10.0"
tensorflow-io-gcs-filesystem = "0.31.0"
termcolor = "2.4.0"
tf-keras-nightly = "2.16.0.dev2023120910"
tifffile = "2023.9.26"
tomli = "2.0.1"
toolz = "0.12.0"
torch = "2.1.0"
torchvision = "0.16.0"
tqdm = "4.66.1"
typing_extensions = "4.8.0"
tzdata = "2023.3"
urllib3 = "2.1.0"
uvicorn = "0.24.0.post1"
virtualenv = "20.24.5"
wcwidth = "0.2.12"
websockets = "11.0.3"
Werkzeug = "3.0.0"
wrapt = "1.14.1"
yapf = "0.40.2"
zipp = "3.17.0"

[dev-packages]

[requires]
python_version = "3.11"
