# Generated by Django 5.0 on 2023-12-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='23331', max_length=13),
            preserve_default=False,
        ),
    ]
